# Generated by Django 3.1.7 on 2021-06-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20210630_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('New', 'Yeni'), ('False', 'Hayır'), ('True', 'Evet')], default='New', max_length=10),
        ),
    ]
