# Generated by Django 3.1.7 on 2021-06-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20210630_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır'), ('New', 'Yeni')], default='New', max_length=10),
        ),
    ]
