# Generated by Django 3.1.7 on 2021-06-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210618_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmessage',
            name='status',
            field=models.CharField(choices=[('Closed', 'Closed'), ('Read', 'Read'), ('New', 'New')], default='New', max_length=10),
        ),
    ]
