# Generated by Django 3.1.7 on 2021-06-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210618_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmessage',
            name='status',
            field=models.CharField(choices=[('Read', 'Read'), ('Closed', 'Closed'), ('New', 'New')], default='New', max_length=10),
        ),
    ]
