# Generated by Django 3.1.7 on 2021-06-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20210630_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmessage',
            name='status',
            field=models.CharField(choices=[('Read', 'Read'), ('Closed', 'Closed'), ('New', 'New')], default='New', max_length=10),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(max_length=250),
        ),
    ]
