# Generated by Django 3.1.7 on 2021-06-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20210630_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmessage',
            name='status',
            field=models.CharField(choices=[('Closed', 'Closed'), ('New', 'New'), ('Read', 'Read')], default='New', max_length=10),
        ),
    ]
