# Generated by Django 3.1.7 on 2021-06-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('haber', 'haber'), ('etkinlik', 'etkinlik'), ('menu', 'menu'), ('duyuru', 'duyuru')], max_length=10),
        ),
    ]
