# Generated by Django 3.1.7 on 2021-06-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20210630_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='category',
            new_name='menu',
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('etkinlik', 'etkinlik'), ('duyuru', 'duyuru'), ('haber', 'haber'), ('menu', 'menu')], max_length=10),
        ),
    ]
