# Generated by Django 3.1.7 on 2021-06-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20210630_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cimages',
            old_name='blog',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('etkinlik', 'etkinlik'), ('menu', 'menu'), ('duyuru', 'duyuru'), ('haber', 'haber')], max_length=10),
        ),
    ]
