# Generated by Django 3.1.7 on 2021-07-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20210630_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('haber', 'haber'), ('etkinlik', 'etkinlik'), ('duyuru', 'duyuru'), ('menu', 'menu')], max_length=10),
        ),
    ]
